#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Dec 01 16:04:50 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b7df4f4d496c4d8b856b1626db2a869a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_even_odd_detector_behav xil_defaultlib.tb_even_odd_detector xil_defaultlib.glbl -log elaborate.log"
xelab -wto b7df4f4d496c4d8b856b1626db2a869a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_even_odd_detector_behav xil_defaultlib.tb_even_odd_detector xil_defaultlib.glbl -log elaborate.log

